language: generic
sudo: true

branches:
  only:
    - dev
    - testing

matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=3.6
    - os: linux
      env: PYTHON_VERSION=3.7
    

# Setup a postgresql instance w/postgis
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

before_install:
  # Create the template database that is used to instantiate the test DB 
  - psql -c 'create database template_postgis;' -U postgres
  - psql template_postgis -U postgres -c "create extension postgis"
  - psql template_postgis -c "create extension postgis_topology"
  - psql -d template_postgis -c "GRANT ALL ON geometry_columns TO PUBLIC;"
  - psql -d template_postgis -c "GRANT ALL ON geography_columns TO PUBLIC;"
  - psql -d template_postgis -c "GRANT ALL ON spatial_ref_sys TO PUBLIC;"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      curl -o miniconda.sh  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create the env
  - conda create -q -n test python=$PYTHON_VERSION
  - source activate test

  # Install dependencies
  - conda env update -n test -f environment.yml
  - export PROJ_LIB=$CONDA_PREFIX/share/proj 
  - pip install travis-sphinx 
  - conda install -c conda-forge nbsphinx

script:
  - autocnet_config=config/test_config.yml pytest -v autocnet
  - travis-sphinx build --source=docs --nowarn # The sphinx build script

after_success:
  - coveralls
 
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6cbe4b65fff6764ed80f
    on_success: always
    on_failure: always
